name: nwhco_app
description: nwhco talk app
publish_to: none
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  audio_waveforms: ^1.3.0
  cached_network_image: ^3.3.0
  connectivity_plus: ^6.1.1
  dartz: ^0.10.1
  device_info_plus: ^11.2.0
  dio: ^5.7.0
  easy_localization: ^3.0.7
  equatable: ^2.0.7
  flutter_bloc: ^8.1.6
  hydrated_bloc: ^9.1.5
  flutter_local_notifications: 18.0.1
  flutter_rating_bar: ^4.0.1
  flutter_staggered_animations: ^1.1.1
  flutter_staggered_grid_view: ^0.7.0
  flutter_svg: ^2.0.16
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path: ^1.9.0
  path_provider: ^2.1.5
  permission_handler: ^11.4.0
  scrollable_positioned_list: ^0.3.8
  shamsi_date: ^1.0.4
  share_plus: ^10.1.3
  shared_preferences: ^2.3.3
  shimmer: ^3.0.0
  string_similarity: ^2.1.1
  url_launcher: ^6.3.1
  uuid: ^4.5.1
  web_socket_channel: ^3.0.3


dev_dependencies:
  build_runner: ^2.4.13
  hive_generator: ^2.0.1
  flutter_lints: ^5.0.0
  analyzer: ^6.5.0


dependency_overrides:
  collection: 1.19.0
  watcher: ^1.1.0
  path: 1.9.0
  intl: 0.19.0


flutter:
  uses-material-design: true
  assets:
    - assets/images/svg/
    - assets/images/png/
    - assets/images/
    - assets/langs/
    - assets/icons/

  fonts:
    - family: sname
      fonts:
        - asset: assets/fonts/sname.ttf
        
    - family: SegoeuiBold
      fonts:    
        - asset: assets/fonts/SegoeUIBold.ttf
          weight: 900         

    - family: Segoeui
      fonts:
        - asset: assets/fonts/segoeui.ttf
          weight: 400

    - family: yekanx
      fonts:
        - asset: assets/fonts/YekanXFaNum-R.ttf

    - family: Faminela
      fonts:
        - asset: assets/fonts/faminela.ttf
          weight: 400